# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mvrnormArma <- function(n, mu, sigma) {
    .Call('_Rcppocc_mvrnormArma', PACKAGE = 'Rcppocc', n, mu, sigma)
}

mvrnormArma2 <- function(n, mu, sigma) {
    .Call('_Rcppocc_mvrnormArma2', PACKAGE = 'Rcppocc', n, mu, sigma)
}

mvrnormArma3 <- function(n, A, invSigma) {
    .Call('_Rcppocc_mvrnormArma3', PACKAGE = 'Rcppocc', n, A, invSigma)
}

mvrnormArma4 <- function(n, A, invSigma) {
    .Call('_Rcppocc_mvrnormArma4', PACKAGE = 'Rcppocc', n, A, invSigma)
}

posterior_r3 <- function(x, wr, sr) {
    .Call('_Rcppocc_posterior_r3', PACKAGE = 'Rcppocc', x, wr, sr)
}

invlogit <- function(lincomb) {
    .Call('_Rcppocc_invlogit', PACKAGE = 'Rcppocc', lincomb)
}

ln_invlogit <- function(lincomb) {
    .Call('_Rcppocc_ln_invlogit', PACKAGE = 'Rcppocc', lincomb)
}

log_not_prob <- function(lincomb) {
    .Call('_Rcppocc_log_not_prob', PACKAGE = 'Rcppocc', lincomb)
}

logitoccDA4 <- function(X, Y, W_vb, siteids, ndraws, ysum, z, nvisits, alpha_m, beta_m, sigma_inv_alpha_p, sigma_inv_beta_p) {
    .Call('_Rcppocc_logitoccDA4', PACKAGE = 'Rcppocc', X, Y, W_vb, siteids, ndraws, ysum, z, nvisits, alpha_m, beta_m, sigma_inv_alpha_p, sigma_inv_beta_p)
}

rpg2 <- function(scale) {
    .Call('_Rcppocc_rpg2', PACKAGE = 'Rcppocc', scale)
}

rpg5 <- function(scale) {
    .Call('_Rcppocc_rpg5', PACKAGE = 'Rcppocc', scale)
}

parallelMatrixRpg <- function(x) {
    .Call('_Rcppocc_parallelMatrixRpg', PACKAGE = 'Rcppocc', x)
}

logitoccPG3 <- function(X, Y, W_vb, siteids, ndraws, ysum, z, nvisits, alpha_m, beta_m, sigma_inv_alpha_p, sigma_inv_beta_p, percent_burn_in) {
    .Call('_Rcppocc_logitoccPG3', PACKAGE = 'Rcppocc', X, Y, W_vb, siteids, ndraws, ysum, z, nvisits, alpha_m, beta_m, sigma_inv_alpha_p, sigma_inv_beta_p, percent_burn_in)
}

rgammadouble <- function(a, b, c) {
    .Call('_Rcppocc_rgammadouble', PACKAGE = 'Rcppocc', a, b, c)
}

rnormdouble <- function(b, c) {
    .Call('_Rcppocc_rnormdouble', PACKAGE = 'Rcppocc', b, c)
}

quadform <- function(X, Xt, dmat) {
    .Call('_Rcppocc_quadform', PACKAGE = 'Rcppocc', X, Xt, dmat)
}

diagtimesX <- function(X, dmat) {
    .Call('_Rcppocc_diagtimesX', PACKAGE = 'Rcppocc', X, dmat)
}

logitoccSPAT <- function(X, W_vb, Y, z, ysum, nvisits, K, Minv, n_obs, siteids, unsurveyed_ind, tau_0, a_tau, b_tau, alpha_m, beta_m, sigma_inv_alpha_p, sigma_inv_beta_p, ndraws, percent_burn_in) {
    .Call('_Rcppocc_logitoccSPAT', PACKAGE = 'Rcppocc', X, W_vb, Y, z, ysum, nvisits, K, Minv, n_obs, siteids, unsurveyed_ind, tau_0, a_tau, b_tau, alpha_m, beta_m, sigma_inv_alpha_p, sigma_inv_beta_p, ndraws, percent_burn_in)
}

